In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression as LR

In [2]:
train = pd.read_csv("/Users/happycatcat523/pyworks/kaggle資料/titanic/train.csv")
test = pd.read_csv("/Users/happycatcat523/pyworks/kaggle資料/titanic/test.csv")
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
train['Age'] = train['Age'].fillna(train['Age'].median())
train['Embarked'] = train['Embarked'].fillna('S')
test['Age'] = test['Age'].fillna(test['Age'].median())
test['Fare'] = test['Fare'].fillna(test['Fare'].median())
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [11]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [12]:
dummy_train = pd.get_dummies(train[['Sex', 'Embarked']])
dummy_test = pd.get_dummies(test[['Sex', 'Embarked']])

In [13]:
train_two = pd.concat([train.drop(["Sex","Embarked"],axis = 1),dummy_train], axis = 1)
test_two = pd.concat([test.drop(["Sex", "Embarked"], axis = 1),dummy_test], axis = 1)

In [15]:
train_three = train_two.drop(['PassengerId', 'Name', 'SibSp', 'Ticket', 'Cabin', 'Parch'], axis = 1)
test_three = test_two.drop(['PassengerId', 'Name', 'SibSp', 'Ticket', 'Cabin', 'Parch'], axis = 1)

In [16]:
X_train = train_three.drop(['Survived'], axis = 1).values
y_train = train_three.Survived.values

In [17]:
lsr = LR()
train_fit = lsr.fit(X_train, y_train)

In [18]:
test_predict = train_fit.predict(test_three)
test_predict_proba = train_fit.predict_proba(test_three)
test_predict

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [19]:
test_predict_proba

array([[0.89551772, 0.10448228],
       [0.59664119, 0.40335881],
       [0.86900201, 0.13099799],
       [0.91095173, 0.08904827],
       [0.41952825, 0.58047175],
       [0.87595247, 0.12404753],
       [0.3812323 , 0.6187677 ],
       [0.77601723, 0.22398277],
       [0.28617873, 0.71382127],
       [0.8949174 , 0.1050826 ],
       [0.91100176, 0.08899824],
       [0.68497046, 0.31502954],
       [0.08104269, 0.91895731],
       [0.90876923, 0.09123077],
       [0.1508657 , 0.8491343 ],
       [0.14215554, 0.85784446],
       [0.7541964 , 0.2458036 ],
       [0.84239233, 0.15760767],
       [0.45541586, 0.54458414],
       [0.46378574, 0.53621426],
       [0.62870743, 0.37129257],
       [0.86022121, 0.13977879],
       [0.09332822, 0.90667178],
       [0.39098755, 0.60901245],
       [0.08780952, 0.91219048],
       [0.95145981, 0.04854019],
       [0.05117933, 0.94882067],
       [0.84798113, 0.15201887],
       [0.65264814, 0.34735186],
       [0.86240087, 0.13759913],
       [0.87308187, 0.12691813],
       [0.76560141, 0.23439859],
       [0.49546977, 0.50453023],
       [0.45231998, 0.54768002],
       [0.45414353, 0.54585647],
       [0.83270755, 0.16729245],
       [0.45539092, 0.54460908],
       [0.41331651, 0.58668349],
       [0.90616487, 0.09383513],
       [0.90778037, 0.09221963],
       [0.89878135, 0.10121865],
       [0.55852747, 0.44147253],
       [0.93846588, 0.06153412],
       [0.24317931, 0.75682069],
       [0.14456912, 0.85543088],
       [0.90627255, 0.09372745],
       [0.56605931, 0.43394069],
       [0.87378686, 0.12621314],
       [0.13596207, 0.86403793],
       [0.51776081, 0.48223919],
       [0.53067242, 0.46932758],
       [0.69058503, 0.30941497],
       [0.193387  , 0.806613  ],
       [0.08081873, 0.91918127],
       [0.69049118, 0.30950882],
       [0.80745308, 0.19254692],
       [0.9278251 , 0.0721749 ],
       [0.90629134, 0.09370866],
       [0.91046517, 0.08953483],
       [0.06401914, 0.93598086],
       [0.8850503 , 0.1149497 ],
       [0.8062683 , 0.1937317 ],
       [0.88792759, 0.11207241],
       [0.32910831, 0.67089169],
       [0.30307723, 0.69692277],
       [0.22667243, 0.77332757],
       [0.30443726, 0.69556274],
       [0.68825918, 0.31174082],
       [0.46705692, 0.53294308],
       [0.1794639 , 0.8205361 ],
       [0.34179951, 0.65820049],
       [0.89614078, 0.10385922],
       [0.46957369, 0.53042631],
       [0.44954704, 0.55045296],
       [0.06476928, 0.93523072],
       [0.4411638 , 0.5588362 ],
       [0.9109917 , 0.0890083 ],
       [0.18672004, 0.81327996],
       [0.79728141, 0.20271859],
       [0.34179951, 0.65820049],
       [0.77600178, 0.22399822],
       [0.77157736, 0.22842264],
       [0.70310816, 0.29689184],
       [0.91100176, 0.08899824],
       [0.70984226, 0.29015774],
       [0.86308916, 0.13691084],
       [0.36124706, 0.63875294],
       [0.39288231, 0.60711769],
       [0.36127104, 0.63872896],
       [0.63736936, 0.36263064],
       [0.41921237, 0.58078763],
       [0.91100964, 0.08899036],
       [0.09195432, 0.90804568],
       [0.9109917 , 0.0890083 ],
       [0.4253646 , 0.5746354 ],
       [0.90628138, 0.09371862],
       [0.28573491, 0.71426509],
       [0.91551095, 0.08448905],
       [0.40658539, 0.59341461],
       [0.92390813, 0.07609187],
       [0.08975827, 0.91024173],
       [0.78134077, 0.21865923],
       [0.87378686, 0.12621314],
       [0.90867372, 0.09132628],
       [0.27448054, 0.72551946],
       [0.91234718, 0.08765282],
       [0.85370249, 0.14629751],
       [0.87378686, 0.12621314],
       [0.91094847, 0.08905153],
       [0.73921525, 0.26078475],
       [0.76879781, 0.23120219],
       [0.36126562, 0.63873438],
       [0.07608155, 0.92391845],
       [0.30756288, 0.69243712],
       [0.19759592, 0.80240408],
       [0.82989561, 0.17010439],
       [0.86384949, 0.13615051],
       [0.28367705, 0.71632295],
       [0.49321345, 0.50678655],
       [0.23608518, 0.76391482],
       [0.16108994, 0.83891006],
       [0.87378686, 0.12621314],
       [0.07267748, 0.92732252],
       [0.91332494, 0.08667506],
       [0.87378686, 0.12621314],
       [0.38457681, 0.61542319],
       [0.89876886, 0.10123114],
       [0.3583986 , 0.6416014 ],
       [0.84698188, 0.15301812],
       [0.90381668, 0.09618332],
       [0.92188175, 0.07811825],
       [0.62118455, 0.37881545],
       [0.45191809, 0.54808191],
       [0.86384949, 0.13615051],
       [0.94167193, 0.05832807],
       [0.90383038, 0.09616962],
       [0.8620908 , 0.1379092 ],
       [0.77824662, 0.22175338],
       [0.4273128 , 0.5726872 ],
       [0.93491498, 0.06508502],
       [0.3330794 , 0.6669206 ],
       [0.09982022, 0.90017978],
       [0.63047361, 0.36952639],
       [0.78616714, 0.21383286],
       [0.65978932, 0.34021068],
       [0.91921366, 0.08078634],
       [0.55350042, 0.44649958],
       [0.89875025, 0.10124975],
       [0.55852747, 0.44147253],
       [0.79558581, 0.20441419],
       [0.05173768, 0.94826232],
       [0.86371144, 0.13628856],
       [0.96354917, 0.03645083],
       [0.51850735, 0.48149265],
       [0.87083248, 0.12916752],
       [0.90385165, 0.09614835],
       [0.08551772, 0.91448228],
       [0.42735135, 0.57264865],
       [0.65978932, 0.34021068],
       [0.44719869, 0.55280131],
       [0.36127414, 0.63872586],
       [0.78091295, 0.21908705],
       [0.22276232, 0.77723768],
       [0.91106017, 0.08893983],
       [0.84325447, 0.15674553],
       [0.4455585 , 0.5544415 ],
       [0.58285249, 0.41714751],
       [0.88577827, 0.11422173],
       [0.06009038, 0.93990962],
       [0.42017981, 0.57982019],
       [0.91102431, 0.08897569],
       [0.86377495, 0.13622505],
       [0.900893  , 0.099107  ],
       [0.86377456, 0.13622544],
       [0.93567025, 0.06432975],
       [0.17031283, 0.82968717],
       [0.19166733, 0.80833267],
       [0.62278412, 0.37721588],
       [0.27182612, 0.72817388],
       [0.14920455, 0.85079545],
       [0.79728141, 0.20271859],
       [0.49874027, 0.50125973],
       [0.07261561, 0.92738439],
       [0.87378686, 0.12621314],
       [0.05084631, 0.94915369],
       [0.83912794, 0.16087206],
       [0.19812354, 0.80187646],
       [0.88503768, 0.11496232],
       [0.44314969, 0.55685031],
       [0.83945347, 0.16054653],
       [0.81348893, 0.18651107],
       [0.55863657, 0.44136343],
       [0.86752021, 0.13247979],
       [0.86547678, 0.13452322],
       [0.67418807, 0.32581193],
       [0.9239192 , 0.0760808 ],
       [0.28309593, 0.71690407],
       [0.39293508, 0.60706492],
       [0.76351632, 0.23648368],
       [0.45537845, 0.54462155],
       [0.35983356, 0.64016644],
       [0.82652429, 0.17347571],
       [0.5408081 , 0.4591919 ],
       [0.14525677, 0.85474323],
       [0.77364543, 0.22635457],
       [0.43939308, 0.56060692],
       [0.41531668, 0.58468332],
       [0.76861962, 0.23138038],
       [0.07049785, 0.92950215],
       [0.90627455, 0.09372545],
       [0.92103899, 0.07896101],
       [0.91105691, 0.08894309],
       [0.72121668, 0.27878332],
       [0.42764874, 0.57235126],
       [0.53359067, 0.46640933],
       [0.65690313, 0.34309687],
       [0.36124706, 0.63875294],
       [0.72676027, 0.27323973],
       [0.09597283, 0.90402717],
       [0.9109917 , 0.0890083 ],
       [0.16582895, 0.83417105],
       [0.89612923, 0.10387077],
       [0.2040553 , 0.7959447 ],
       [0.89614827, 0.10385173],
       [0.11823108, 0.88176892],
       [0.33980464, 0.66019536],
       [0.9013306 , 0.0986694 ],
       [0.36127104, 0.63872896],
       [0.93729655, 0.06270345],
       [0.82350193, 0.17649807],
       [0.70514288, 0.29485712],
       [0.08014377, 0.91985623],
       [0.89624556, 0.10375444],
       [0.8737754 , 0.1262246 ],
       [0.51536271, 0.48463729],
       [0.8934634 , 0.1065366 ],
       [0.68356953, 0.31643047],
       [0.83857443, 0.16142557],
       [0.18587171, 0.81412829],
       [0.0983923 , 0.9016077 ],
       [0.12427507, 0.87572493],
       [0.32698876, 0.67301124],
       [0.54524572, 0.45475428],
       [0.9110023 , 0.0889977 ],
       [0.90998197, 0.09001803],
       [0.64874192, 0.35125808],
       [0.20268675, 0.79731325],
       [0.8449376 , 0.1550624 ],
       [0.23608518, 0.76391482],
       [0.33994753, 0.66005247],
       [0.12181764, 0.87818236],
       [0.89345798, 0.10654202],
       [0.41752172, 0.58247828],
       [0.90372748, 0.09627252],
       [0.922818  , 0.077182  ],
       [0.91102431, 0.08897569],
       [0.87378686, 0.12621314],
       [0.91327398, 0.08672602],
       [0.19021967, 0.80978033],
       [0.89614982, 0.10385018],
       [0.93013868, 0.06986132],
       [0.89614389, 0.10385611],
       [0.23652073, 0.76347927],
       [0.28441601, 0.71558399],
       [0.70891829, 0.29108171],
       [0.91100176, 0.08899824],
       [0.5637874 , 0.4362126 ],
       [0.91102431, 0.08897569],
       [0.45539092, 0.54460908],
       [0.88498753, 0.11501247],
       [0.56405372, 0.43594628],
       [0.87378686, 0.12621314],
       [0.05385252, 0.94614748],
       [0.35983356, 0.64016644],
       [0.86377495, 0.13622505],
       [0.1930108 , 0.8069892 ],
       [0.78825593, 0.21174407],
       [0.83803896, 0.16196104],
       [0.7962392 , 0.2037608 ],
       [0.75833587, 0.24166413],
       [0.42719222, 0.57280778],
       [0.82830406, 0.17169594],
       [0.36127104, 0.63872896],
       [0.23563419, 0.76436581],
       [0.28891845, 0.71108155],
       [0.929743  , 0.070257  ],
       [0.91104387, 0.08895613],
       [0.52620855, 0.47379145],
       [0.86377456, 0.13622544],
       [0.9109917 , 0.0890083 ],
       [0.55593718, 0.44406282],
       [0.3813612 , 0.6186388 ],
       [0.86377456, 0.13622544],
       [0.71730167, 0.28269833],
       [0.92962467, 0.07037533],
       [0.90866566, 0.09133434],
       [0.07844677, 0.92155323],
       [0.86240087, 0.13759913],
       [0.57575624, 0.42424376],
       [0.91551535, 0.08448465],
       [0.92189768, 0.07810232],
       [0.69058288, 0.30941712],
       [0.84981678, 0.15018322],
       [0.90377384, 0.09622616],
       [0.36127104, 0.63872896],
       [0.2286679 , 0.7713321 ],
       [0.55479378, 0.44520622],
       [0.82913275, 0.17086725],
       [0.72685139, 0.27314861],
       [0.58147104, 0.41852896],
       [0.88785451, 0.11214549],
       [0.8461365 , 0.1538635 ],
       [0.91102268, 0.08897732],
       [0.42921041, 0.57078959],
       [0.11513087, 0.88486913],
       [0.29846531, 0.70153469],
       [0.62563657, 0.37436343],
       [0.7423357 , 0.2576643 ],
       [0.91100447, 0.08899553],
       [0.75522624, 0.24477376],
       [0.90867372, 0.09132628],
       [0.85693279, 0.14306721],
       [0.77824662, 0.22175338],
       [0.60014156, 0.39985844],
       [0.11140634, 0.88859366],
       [0.90138395, 0.09861605],
       [0.15857819, 0.84142181],
       [0.56327052, 0.43672948],
       [0.79091549, 0.20908451],
       [0.75270444, 0.24729556],
       [0.34483228, 0.65516772],
       [0.52371319, 0.47628681],
       [0.86377495, 0.13622505],
       [0.29061757, 0.70938243],
       [0.91100176, 0.08899824],
       [0.57958353, 0.42041647],
       [0.80633112, 0.19366888],
       [0.89923331, 0.10076669],
       [0.77067322, 0.22932678],
       [0.86377456, 0.13622544],
       [0.73685117, 0.26314883],
       [0.92190903, 0.07809097],
       [0.90689741, 0.09310259],
       [0.09474832, 0.90525168],
       [0.91057004, 0.08942996],
       [0.3794587 , 0.6205413 ],
       [0.77824662, 0.22175338],
       [0.41472665, 0.58527335],
       [0.76819011, 0.23180989],
       [0.24725889, 0.75274111],
       [0.09397796, 0.90602204],
       [0.77364543, 0.22635457],
       [0.7269063 , 0.2730937 ],
       [0.86630011, 0.13369989],
       [0.27827212, 0.72172788],
       [0.70901824, 0.29098176],
       [0.20128328, 0.79871672],
       [0.91100284, 0.08899716],
       [0.87378686, 0.12621314],
       [0.47514244, 0.52485756],
       [0.87217795, 0.12782205],
       [0.14124721, 0.85875279],
       [0.24725889, 0.75274111],
       [0.91095173, 0.08904827],
       [0.05576698, 0.94423302],
       [0.44314969, 0.55685031],
       [0.86308877, 0.13691123],
       [0.41416989, 0.58583011],
       [0.09424946, 0.90575054],
       [0.70281873, 0.29718127],
       [0.75292899, 0.24707101],
       [0.06169185, 0.93830815],
       [0.70745589, 0.29254411],
       [0.85421856, 0.14578144],
       [0.17579189, 0.82420811],
       [0.08120305, 0.91879695],
       [0.42023861, 0.57976139],
       [0.75292899, 0.24707101],
       [0.73374397, 0.26625603],
       [0.84297294, 0.15702706],
       [0.87378686, 0.12621314],
       [0.87060095, 0.12939905],
       [0.45410429, 0.54589571],
       [0.39814245, 0.60185755],
       [0.7831394 , 0.2168606 ],
       [0.20619291, 0.79380709],
       [0.90383591, 0.09616409],
       [0.89456948, 0.10543052],
       [0.85370961, 0.14629039],
       [0.84777957, 0.15222043],
       [0.51684745, 0.48315255],
       [0.16848565, 0.83151435],
       [0.871837  , 0.128163  ],
       [0.86477431, 0.13522569],
       [0.91462938, 0.08537062],
       [0.07224268, 0.92775732],
       [0.86410752, 0.13589248],
       [0.10035246, 0.89964754],
       [0.89877038, 0.10122962],
       [0.88582522, 0.11417478],
       [0.0915071 , 0.9084929 ],
       [0.8307252 , 0.1692748 ],
       [0.05128019, 0.94871981],
       [0.48347531, 0.51652469],
       [0.55241363, 0.44758637],
       [0.64667438, 0.35332562],
       [0.76351632, 0.23648368],
       [0.56510869, 0.43489131],
       [0.36127646, 0.63872354],
       [0.29588187, 0.70411813],
       [0.36127104, 0.63872896],
       [0.0811386 , 0.9188614 ],
       [0.46251721, 0.53748279],
       [0.9109917 , 0.0890083 ],
       [0.07773631, 0.92226369],
       [0.93425359, 0.06574641],
       [0.9109917 , 0.0890083 ],
       [0.86233602, 0.13766398]])

In [21]:
PassengerId = np.array(test['PassengerId']).astype(int)
my_solution = pd.DataFrame(test_predict, PassengerId, columns = ['Survived'])
my_solution.to_csv("logistic05.csv", index_label = ['PassengerId'])